name: simple_stream
description: A simple application that reads integers from a stream and adds their values together.
homepage: https://www.dartlang.org/docs/tutorials/streams/

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
