name: mini_with_style
description: A sample application
homepage: https://dart.dev/tutorials/web/low-level-html/connect-dart-html

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
