name: read_file
description: A simple app that reads a file (specified on the command line), decodes, and prints it out.
homepage: https://dart.dev/tutorials/language/streams

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
