name: futures_api
description: A sample application that reads a file on dartlang using the Futures API, and prints the contents.
homepage: https://www.dartlang.org/docs/tutorials/futures/

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.7.0
